#!/bin/bash
namefile=${!#}
namefile=${namefile%.*}
#datetemp=$(date +"%Y%m%d")
#newdir=${namefile}_${datetemp}_l
newdir=$1
shift

##delete ","
parameters=""
for param in "$@"
do
	if [[ ${param: -1} = "," ]]
	then
		param=${param:0:${#param}-1}
	fi
	parameters="$parameters $param"
done
if [[ ${#parameters} -gt 0 ]]
then
	parameters=${parameters:1}
fi

##create $sources
sources=""
for param in $parameters
do
	if [[ ${param##*.} = "cpp" ]]
	then
    	sources="$sources $param"
	fi
done
if [[ ${#sources} -gt 0 ]]
then
	sources=${sources:1}
fi

##test directory
if [ -d ../$newdir ];
then
	echo "../${newdir} - directory exist!"
	exit 1
fi

##create directory and files
mkdir ../${newdir}
for param in $parameters
do
	cp lesson.cpp ../${newdir}/$param
#	subl ../${newdir}/$param
done
sed -e "s/SOURCES=main.cpp/SOURCES=${sources}/; s/EXECUTABLE=hello/EXECUTABLE=${namefile}/" ./makefile > ../${newdir}/makefile
sed "s/TARGET=hello/TARGET=${namefile}/" ./run > ../${newdir}/run

mkdir ../${newdir}/.vscode
cp .vscode/tasks.json ../${newdir}/.vscode/tasks.json
sed "s/\${workspaceFolder}\/lesson/\${workspaceFolder}\/${namefile}/" .vscode/launch.json > ../${newdir}/.vscode/launch.json

cd ../${newdir}
lxterminal